"""Generate ALSA configuration from SIREN UI state."""

from __future__ import annotations

from dataclasses import dataclass

from siren.devices import DeviceConfig


@dataclass
class CombinedNames:
    base: str = "bloodsiren"
    input_suffix: str = "_in"
    output_suffix: str = "_out"


def _sanitize(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c == "_" else "_" for c in name.strip())
    while "__" in cleaned:
        cleaned = cleaned.replace("__", "_")
    return cleaned.strip("_") or "device"


def _combined_in_name(names: CombinedNames) -> str:
    return _sanitize(names.base + names.input_suffix)


def _combined_out_name(names: CombinedNames) -> str:
    return _sanitize(names.base + names.output_suffix)


def _combined_full_name(names: CombinedNames) -> str:
    return _sanitize(names.base)


def generate_asoundrc(
    devices: list[DeviceConfig],
    names: CombinedNames,
) -> str:
    combined = [d for d in devices if d.combine]
    if not combined:
        raise ValueError("Select at least one device to combine.")

    primary = combined[0]
    primary_alias = _sanitize(primary.alias or primary.device.card_id)

    in_pcm = _combined_in_name(names)
    out_pcm = _combined_out_name(names)
    full_pcm = _combined_full_name(names)

    lines = [
        "# Generated by SIREN",
        "# IN  = route-constrained multi capture (Waveform-safe channel count)",
        "# OUT = stereo on primary interface only",
        "# Do NOT use asym+null or 8-channel multi for output.",
        "",
    ]

    for cfg in devices:
        alias = _sanitize(cfg.alias or cfg.device.card_id)
        lines.extend(
            [
                f"pcm.{alias} {{",
                "    type hw",
                f"    card {cfg.device.card_id}",
                "    device 0",
                "}",
                "",
            ]
        )

    in_slaves: list[tuple[str, str, int]] = []
    in_bindings: list[tuple[str, int, str]] = []

    for idx, cfg in enumerate(combined):
        letter = chr(ord("a") + idx)
        alias = _sanitize(cfg.alias or cfg.device.card_id)
        channels = max(cfg.device.capture_channels, cfg.device.playback_channels, 1)
        cfg.ensure_ports(channels)
        in_slaves.append((letter, alias, channels))
        for port_idx, port in enumerate(cfg.ports[:channels]):
            if port.input or port.combined:
                label = port.label or f"{alias} port {port_idx + 1}"
                in_bindings.append((letter, port_idx, label))

    if not in_bindings:
        raise ValueError("No input/combined ports selected for capture.")

    in_channels = len(in_bindings)

    lines.append(f"pcm.{in_pcm} {{")
    lines.append("    type route")
    lines.append("    slave.pcm {")
    lines.append("        type multi")
    for letter, alias, ch in in_slaves:
        lines.append(f'        slaves.{letter}.pcm "{alias}"')
        lines.append(f"        slaves.{letter}.channels {ch}")
    for bind_idx, (letter, port_idx, label) in enumerate(in_bindings):
        lines.append(
            f"        bindings.{bind_idx} {{ slave {letter}; channel {port_idx}; }}  # {label}"
        )
    lines.append("    }")
    lines.append(f"    slave.channels {in_channels}")
    for ch in range(in_channels):
        lines.append(f"    ttable.{ch}.{ch} 1")
    lines.append("}")
    lines.append("")

    primary_out = f"{primary_alias}_out"
    lines.extend(
        [
            f"pcm.{primary_out} {{",
            "    type route",
            f'    slave.pcm "{primary_alias}"',
            "    slave.channels 4",
            "    ttable.0.0 1",
            "    ttable.1.1 1",
            "    ttable.0.2 1",
            "    ttable.1.3 1",
            "}",
            "",
            f"pcm.{primary_alias}_playback {{",
            "    type plug",
            f'    slave.pcm "{primary_out}"',
            "    slave.channels 2",
            "}",
            "",
            f"pcm.{out_pcm} {{",
            "    type plug",
            f'    slave.pcm "{primary_out}"',
            "    slave.channels 2",
            "}",
            "",
            f"pcm.{full_pcm} {{",
            "    type asym",
            f'    capture.pcm "{in_pcm}"',
            f'    playback.pcm "{out_pcm}"',
            "}",
            "",
        ]
    )

    for cfg in combined:
        alias = _sanitize(cfg.alias or cfg.device.card_id)
        if alias == primary_alias:
            continue
        lines.extend(
            [
                f"pcm.{alias}_playback {{",
                "    type plug",
                "    slave.pcm {",
                "        type route",
                f'        slave.pcm "{alias}"',
                "        slave.channels 4",
                "        ttable.0.0 1",
                "        ttable.1.1 1",
                "        ttable.0.2 1",
                "        ttable.1.3 1",
                "    }",
                "}",
                "",
            ]
        )

    return "\n".join(lines)
