"""Generate system-level audio configs and apply them."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from siren.config import CombinedNames, _combined_in_name, _sanitize, generate_asoundrc
from siren.devices import DeviceConfig
from siren.profile import CONFIG_DIR


@dataclass
class DeployResult:
    messages: list[str]
    errors: list[str]


def generate_udev_rules(
    hub_primary: str,
    hub_secondary: str,
    primary_alias: str,
    secondary_alias: str,
    vendor: str,
    product: str,
) -> str:
    primary_id = _sanitize(primary_alias).upper()
    secondary_id = _sanitize(secondary_alias).upper()
    primary_seg = f"1-{hub_primary}"
    secondary_seg = f"1-{hub_secondary}"
    return f"""# Generated by SIREN
SUBSYSTEM!="sound", GOTO="siren_end"
ACTION!="add", GOTO="siren_end"
ATTR{{idVendor}}!="{vendor}", GOTO="siren_end"
ATTR{{idProduct}}!="{product}", GOTO="siren_end"

DEVPATH=="*/{primary_seg}/*/*/sound/card?", ATTR{{id}}="{primary_id}"
DEVPATH=="*/{secondary_seg}/*/*/sound/card?", ATTR{{id}}="{secondary_id}"

LABEL="siren_end"
"""


def generate_pipewire_combine(
    combined: CombinedNames,
    configs: list[DeviceConfig],
) -> str:
    combined_devs = [c for c in configs if c.combine]
    in_name = _combined_in_name(combined)
    channel_positions = " ".join(f"AUX{i}" for i in range(8))

    rules: list[str] = []
    bind_index = 0
    for cfg in combined_devs:
        card_id = cfg.device.card_id
        ch = min(4, cfg.device.capture_channels or 4)
        positions = " ".join(f"AUX{bind_index + i}" for i in range(ch))
        bind_index += ch
        rules.append(
            f"""                {{ matches = [
                    {{ media.class = "Audio/Source"
                      object.path = "alsa:pcm:{card_id}:0:capture"
                    }}
                  ]
                  actions = {{ create-stream = {{
                      audio.position = [ FL FR RL RR ]
                      combine.audio.position = [ {positions} ]
                  }} }}
                }}"""
        )
        alias_id = _sanitize(cfg.alias or card_id).upper()
        if alias_id != card_id.upper():
            rules.append(
                f"""                {{ matches = [
                    {{ media.class = "Audio/Source"
                      object.path = "alsa:pcm:{alias_id}:0:capture"
                    }}
                  ]
                  actions = {{ create-stream = {{
                      audio.position = [ FL FR RL RR ]
                      combine.audio.position = [ {positions} ]
                  }} }}
                }}"""
            )

    rules_text = "\n".join(rules)
    return f"""# Generated by SIREN — PipeWire combined capture source

context.modules = [
    {{ name = libpipewire-module-combine-stream
        args = {{
            combine.mode = source
            node.name = "combine_source_{_sanitize(combined.base)}"
            node.description = "{combined.base}"
            combine.latency-compensate = true
            combine.props = {{
                audio.position = [ {channel_positions} ]
            }}
            stream.props = {{
                stream.dont-remix = true
            }}
            stream.rules = [
{rules_text}
            ]
        }}
    }}
]
"""


def generate_wireplumber_rule(vendor: str, product: str) -> str:
    return f"""# Generated by SIREN — keep duplicate-serial USB interfaces separate

monitor.alsa.rules = [
  {{
    matches = [
      {{
        device.name = "~alsa_card.usb-*{vendor}*{product}*"
      }}
    ]
    actions = {{
      update-props = {{
        api.alsa.use-acp = false
      }}
    }}
  }}
]
"""


def deploy_all(
    configs: list[DeviceConfig],
    combined: CombinedNames,
    hub_primary: str,
    hub_secondary: str,
    usb_vendor: str,
    usb_product: str,
    install_pipewire: bool,
    install_wireplumber: bool,
    install_udev: bool,
) -> DeployResult:
    result = DeployResult(messages=[], errors=[])
    combined_devs = [c for c in configs if c.combine]

    if len(combined_devs) < 1:
        result.errors.append("Select at least one device to combine.")
        return result

    try:
        asoundrc = generate_asoundrc(configs, combined)
    except ValueError as exc:
        result.errors.append(str(exc))
        return result

    home = Path.home()
    asound_path = home / ".asoundrc"
    asound_path.write_text(asoundrc, encoding="utf-8")
    result.messages.append(f"Wrote {asound_path}")

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    (CONFIG_DIR / "asoundrc.generated").write_text(asoundrc, encoding="utf-8")

    if install_pipewire:
        pw_dir = home / ".config" / "pipewire" / "pipewire.conf.d"
        pw_dir.mkdir(parents=True, exist_ok=True)
        pw_path = pw_dir / "90-siren-combine.conf"
        pw_path.write_text(generate_pipewire_combine(combined, configs), encoding="utf-8")
        result.messages.append(f"Wrote {pw_path}")

    if install_wireplumber:
        wp_dir = home / ".config" / "wireplumber" / "wireplumber.conf.d"
        wp_dir.mkdir(parents=True, exist_ok=True)
        wp_path = wp_dir / "51-siren-devices.conf"
        wp_path.write_text(generate_wireplumber_rule(usb_vendor, usb_product), encoding="utf-8")
        result.messages.append(f"Wrote {wp_path}")

    primary_alias = "blood"
    secondary_alias = "siren"
    for cfg in combined_devs:
        if cfg.device.hub_port == hub_primary:
            primary_alias = cfg.alias or primary_alias
        if cfg.device.hub_port == hub_secondary:
            secondary_alias = cfg.alias or secondary_alias

    udev_text = generate_udev_rules(
        hub_primary, hub_secondary, primary_alias, secondary_alias, usb_vendor, usb_product
    )
    udev_local = CONFIG_DIR / "99-siren-audio.rules"
    udev_local.write_text(udev_text, encoding="utf-8")
    result.messages.append(f"Wrote {udev_local}")

    if install_udev:
        udev_dst = Path("/etc/udev/rules.d/99-siren-audio.rules")
        proc = subprocess.run(
            ["sudo", "cp", str(udev_local), str(udev_dst)],
            capture_output=True,
            text=True,
        )
        if proc.returncode == 0:
            subprocess.run(["sudo", "udevadm", "control", "--reload-rules"], check=False)
            result.messages.append(f"Installed {udev_dst}")
        else:
            result.errors.append(
                "Could not install udev rules (sudo required). "
                f"Run: sudo cp {udev_local} {udev_dst}"
            )

    proc = subprocess.run(
        ["systemctl", "--user", "restart", "wireplumber", "pipewire", "pipewire-pulse"],
        capture_output=True,
        text=True,
    )
    if proc.returncode == 0:
        result.messages.append("Restarted PipeWire / WirePlumber")
    else:
        result.errors.append(proc.stderr.strip() or "Failed to restart audio services")

    in_dev = _combined_in_name(combined)
    in_channels = max(1, sum(min(4, c.device.capture_channels or 4) for c in combined_devs))
    test = subprocess.run(
        [
            "arecord", "-D", in_dev,
            "-c", str(in_channels),
            "-r", "48000", "-f", "S24_3LE",
            "-d", "1", "/dev/null",
        ],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if test.returncode == 0:
        result.messages.append(f"Capture test OK on {in_dev}")
    else:
        result.errors.append(f"Capture test failed on {in_dev}: {test.stderr.strip()}")

    playback_alias = "blood"
    for cfg in combined_devs:
        if cfg.device.hub_port:
            playback_alias = _sanitize(cfg.alias or cfg.device.card_id)
            break
    playback_dev = f"{playback_alias}_playback"
    tone = Path("/tmp/siren_playback_test.wav")
    try:
        import math
        import struct
        import wave

        rate = 48000
        dur = 0.5
        freq = 880
        n = int(rate * dur)
        with wave.open(str(tone), "w") as w:
            w.setnchannels(2)
            w.setsampwidth(2)
            w.setframerate(rate)
            frames = bytearray()
            for i in range(n):
                sample = int(32767 * 0.7 * math.sin(2 * math.pi * freq * i / rate))
                frames += struct.pack("<hh", sample, sample)
            w.writeframes(frames)
        play_source = str(tone)
    except OSError:
        play_source = "/dev/zero"

    play = subprocess.run(
        [
            "aplay", "-D", playback_dev,
            "-c", "2",
            "-r", "48000", "-f", "S16_LE",
            "-d", "1", play_source,
        ],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if play.returncode == 0:
        result.messages.append(f"Playback test OK on {playback_dev}")
    else:
        result.errors.append(f"Playback test failed on {playback_dev}: {play.stderr.strip()}")

    return result
