#!/usr/bin/env bash
# List powered-hub USB paths for both HIFI units and write ~/.config/bloodsiren/hub-ports.env
set -euo pipefail

CONFIG_DIR="${HOME}/.config/bloodsiren"
OUT="${CONFIG_DIR}/hub-ports.env"

mkdir -p "$CONFIG_DIR"

declare -a PORTS=()
declare -a CARD_INFO=()

while IFS= read -r path; do
  [[ -e "$path" ]] || continue
  port=$(basename "$path" | sed -n 's/.*usb-0:\([^:]*\):1\.1/\1/p')
  [[ -n "$port" ]] || continue
  card_num=$(basename "$(readlink -f "$path")" | sed 's/controlC//')
  card_id=$(cat "/sys/class/sound/card${card_num}/id" 2>/dev/null || echo "?")
  [[ "$card_id" == "AUDIO" || "$card_id" == "AUDIO_1" ]] || continue
  PORTS+=("$port")
  CARD_INFO+=("card${card_num}:${card_id}")
done < <(ls -1 /dev/snd/by-path/*usb-0:*:1.1 2>/dev/null | sort -u)

echo "USB HIFI AUDIO hub ports (interface :1.1)"
echo "=========================================="
if [[ ${#PORTS[@]} -eq 0 ]]; then
  echo "No HIFI units found. Use a POWERED USB hub for both boxes."
  exit 1
fi

for i in "${!PORTS[@]}"; do
  echo "  port ${PORTS[$i]}  ->  ${CARD_INFO[$i]}"
done
echo

sorted=($(printf '%s\n' "${PORTS[@]}" | sort -V))
BLOOD="${sorted[0]}"
SIREN=""
if [[ ${#sorted[@]} -ge 2 ]]; then
  SIREN="${sorted[1]}"
fi
if [[ ${#sorted[@]} -gt 2 ]]; then
  echo "Warning: ${#sorted[@]} HIFI paths; using ${BLOOD} + ${SIREN}. Edit ${OUT} if wrong."
fi
if [[ ${#PORTS[@]} -eq 1 ]]; then
  echo "Only one unit — wrote blood port; 4 inputs until the second is plugged in."
fi

cat > "$OUT" <<EOF
# Generated by detect-hub-ports.sh at $(date -Is)
# blood = playback + inputs 1-4 | siren = inputs 5-8 (empty if second unit absent)
HUB_PORT_BLOOD=${BLOOD}
HUB_PORT_SIREN=${SIREN}
EOF

echo "Wrote ${OUT}:"
cat "$OUT"
echo
echo "Run: scripts/refresh-bloodsiren.sh"
