#!/usr/bin/env bash
set -euo pipefail

# Powered USB hub paths — from ~/.config/bloodsiren/hub-ports.env or env vars.
ENV_FILE="${HOME}/.config/bloodsiren/hub-ports.env"
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"
# Ports from env file only — no example defaults (empty siren = 4 inputs).
HUB_PORT_BLOOD="${HUB_PORT_BLOOD:-}"
HUB_PORT_SIREN="${HUB_PORT_SIREN:-}"

find_card_for_hub_port() {
  local port="$1"
  for path in /dev/snd/by-path/*"usb-0:${port}"*; do
    [[ -e "$path" ]] || continue
    local card_num card_id
    card_num=$(basename "$(readlink -f "$path")" | sed 's/controlC//')
    card_id=$(cat "/sys/class/sound/card${card_num}/id")
    echo "$card_id"
    return 0
  done
  return 1
}

CARD_BLOOD=""
CARD_SIREN=""
[[ -n "$HUB_PORT_BLOOD" ]] && CARD_BLOOD=$(find_card_for_hub_port "$HUB_PORT_BLOOD" 2>/dev/null || true)
[[ -n "$HUB_PORT_SIREN" ]] && CARD_SIREN=$(find_card_for_hub_port "$HUB_PORT_SIREN" 2>/dev/null || true)

if [[ -z "$CARD_BLOOD" && -z "$CARD_SIREN" ]]; then
  echo "No USB HIFI AUDIO on configured hub ports (blood=${HUB_PORT_BLOOD:-<unset>} siren=${HUB_PORT_SIREN:-<unset>}). Run scripts/detect-hub-ports.sh" >&2
  exit 1
fi

PRIMARY_CARD="${CARD_BLOOD:-$CARD_SIREN}"
IN_CHANNELS=0
[[ -n "$CARD_BLOOD" ]] && IN_CHANNELS=$((IN_CHANNELS + 4))
[[ -n "$CARD_SIREN" ]] && IN_CHANNELS=$((IN_CHANNELS + 4))

{
  cat <<EOF
# Auto-generated by refresh-bloodsiren.sh
# Waveform: in=bloodsiren_in  out=blood_playback  (do NOT use bloodsiren duplex — 256ch bug)
# Do NOT wrap with asym+null — Waveform probes null as 10000 channels and crashes.

EOF

  [[ -n "$CARD_BLOOD" ]] && cat <<EOF
pcm.blood {
    type hw
    card ${CARD_BLOOD}
    device 0
}

EOF

  [[ -n "$CARD_SIREN" ]] && cat <<EOF
pcm.siren {
    type hw
    card ${CARD_SIREN}
    device 0
}

EOF

  echo "pcm.bloodsiren_in {"
  echo "    type multi"
  if [[ -n "$CARD_BLOOD" ]]; then
    echo '    slaves.a.pcm "blood"'
    echo "    slaves.a.channels 4"
  fi
  if [[ -n "$CARD_SIREN" ]]; then
    letter=$([[ -n "$CARD_BLOOD" ]] && echo b || echo a)
    echo "    slaves.${letter}.pcm \"siren\""
    echo "    slaves.${letter}.channels 4"
  fi
  idx=0
  if [[ -n "$CARD_BLOOD" ]]; then
    for i in 0 1 2 3; do
      echo "    bindings.$idx { slave a; channel $i; }"
      idx=$((idx + 1))
    done
  fi
  if [[ -n "$CARD_SIREN" ]]; then
    letter=$([[ -n "$CARD_BLOOD" ]] && echo b || echo a)
    for i in 0 1 2 3; do
      echo "    bindings.$idx { slave ${letter}; channel $i; }"
      idx=$((idx + 1))
    done
  fi
  echo "}"
  echo ""

  [[ -n "$CARD_BLOOD" ]] && cat <<EOF
pcm.blood_out {
    type route
    slave.pcm "blood"
    slave.channels 4
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
}

pcm.blood_playback {
    type plug
    slave.pcm "blood_out"
    slave.channels 2
}

# Waveform can probe blood_playback as broken and fall back to PipeWire "default"
# (laptop speakers). Use hw card name for Waveform — opens 4ch, maps master to 0+1.
pcm.waveform_out {
    type plug
    slave.pcm "blood"
    slave.channels 4
}

pcm.bloodsiren_out {
    type plug
    slave.pcm "blood_out"
    slave.channels 2
}

# Stereo master mix for Waveform — avoids route-plugin 256ch probe on blood_playback.
pcm.blood_mix_out {
    type plug
    slave.pcm "blood"
    slave.channels 4
}

pcm.blood_test_ch0 {
    type route
    slave.pcm "blood"
    slave.channels 4
    ttable.0.0 1
}
pcm.blood_test_ch1 {
    type route
    slave.pcm "blood"
    slave.channels 4
    ttable.0.1 1
}
pcm.blood_test_ch2 {
    type route
    slave.pcm "blood"
    slave.channels 4
    ttable.0.2 1
}
pcm.blood_test_ch3 {
    type route
    slave.pcm "blood"
    slave.channels 4
    ttable.0.3 1
}

EOF

  [[ -n "$CARD_SIREN" ]] && cat <<EOF
pcm.siren_playback {
    type plug
    slave.pcm {
        type route
        slave.pcm "siren"
        slave.channels 4
        ttable.0.0 1
        ttable.1.1 1
        ttable.0.2 1
        ttable.1.3 1
    }
}

EOF
} > "${HOME}/.asoundrc"

echo "bloodsiren configured:"
[[ -n "$CARD_BLOOD" ]] && echo "  blood  (port ${HUB_PORT_BLOOD}) -> in ch 1-4, default stereo out"
[[ -n "$CARD_SIREN" ]] && echo "  siren  (port ${HUB_PORT_SIREN}) -> in ch 5-8"
[[ -z "$CARD_SIREN" ]] && echo "  WARNING: siren not plugged — 4 inputs only" >&2
echo "  Waveform: in=bloodsiren_in  out=blood_mix_out  (stereo master sum on blood)"
