#!/usr/bin/env bash
set -euo pipefail

BLOOD_PORT="${BLOOD_PORT:-2.3}"
SIREN_PORT="${SIREN_PORT:-2.4}"
RATE="${RATE:-48000}"
WORKDIR="${WORKDIR:-$HOME/Downloads/waveformstuff}"
OUT="${ASOUNDRC_OUT:-$HOME/.asoundrc}"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

find_pcm_link() {
  local port="$1"
  local dir="/dev/snd/by-path"
  [[ -d "$dir" ]] || die "$dir does not exist"

  local link
  for link in "$dir"/*"usb-0:${port}"*; do
    [[ -e "$link" ]] || continue
    printf '%s\n' "$link"
    return 0
  done
  die "Could not find /dev/snd/by-path link for hub port $port"
}

card_from_control_link() {
  local link="$1"
  local target base
  target="$(readlink -f "$link")"
  base="$(basename "$target")"
  [[ "$base" =~ ^controlC([0-9]+)$ ]] || die "$link did not resolve to controlC#: $target"
  printf '%s\n' "${BASH_REMATCH[1]}"
}

card_id() {
  local card="$1"
  if [[ -r "/proc/asound/card${card}/id" ]]; then
    tr -d '[:space:]' < "/proc/asound/card${card}/id"
  else
    printf 'card%s' "$card"
  fi
}

blood_link="$(find_pcm_link "$BLOOD_PORT")"
siren_link="$(find_pcm_link "$SIREN_PORT")"

blood_card="$(card_from_control_link "$blood_link")"
siren_card="$(card_from_control_link "$siren_link")"

[[ "$blood_card" != "$siren_card" ]] || die "blood and siren resolved to same ALSA card $blood_card"

timestamp="$(date +%Y%m%d-%H%M%S)"
if [[ -f "$OUT" ]]; then
  cp -a "$OUT" "${OUT}.bak-${timestamp}"
fi

cat > "$OUT" <<EOF
# Generated by bloodsiren-kit at $(date -Is)
# blood hub port: $BLOOD_PORT -> card $blood_card ($(card_id "$blood_card"))
# siren hub port: $SIREN_PORT -> card $siren_card ($(card_id "$siren_card"))

pcm.blood_hw {
    type hw
    card $blood_card
    device 0
}

ctl.blood_hw {
    type hw
    card $blood_card
}

pcm.siren_hw {
    type hw
    card $siren_card
    device 0
}

ctl.siren_hw {
    type hw
    card $siren_card
}

# 8-channel capture only.
# Channels 0-3 = blood capture 1-4.
# Channels 4-7 = siren capture 1-4.
pcm.bloodsiren_in_raw {
    type multi
    slaves.a.pcm "blood_hw"
    slaves.a.channels 4
    slaves.b.pcm "siren_hw"
    slaves.b.channels 4

    bindings.0.slave a
    bindings.0.channel 0
    bindings.1.slave a
    bindings.1.channel 1
    bindings.2.slave a
    bindings.2.channel 2
    bindings.3.slave a
    bindings.3.channel 3

    bindings.4.slave b
    bindings.4.channel 0
    bindings.5.slave b
    bindings.5.channel 1
    bindings.6.slave b
    bindings.6.channel 2
    bindings.7.slave b
    bindings.7.channel 3
}

pcm.bloodsiren_in {
    type plug
    slave.pcm "bloodsiren_in_raw"
    slave.channels 8
    slave.rate $RATE
}

# Stereo app output mirrored to all four USB playback channels (FL/FR/RL/RR).
pcm.blood_out {
    type route
    slave.pcm "blood_hw"
    slave.channels 4
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
}

pcm.blood_playback {
    type plug
    slave.pcm "blood_out"
    slave.channels 2
    slave.rate $RATE
}

# Waveform opens 4ch on blood directly (avoids some probe failures on blood_playback).
pcm.waveform_out {
    type plug
    slave.pcm "blood_hw"
    slave.channels 4
    slave.rate $RATE
}

ctl.waveform_out {
    type hw
    card $blood_card
}

# Optional explicit stereo capture view of blood only.
pcm.blood_in_4ch {
    type plug
    slave.pcm "blood_hw"
    slave.channels 4
    slave.rate $RATE
}

# Optional explicit stereo capture view of siren only.
pcm.siren_in_4ch {
    type plug
    slave.pcm "siren_hw"
    slave.channels 4
    slave.rate $RATE
}

# Deliberately boring default: laptop/PipeWire default remains outside this file.
# Do not point Waveform at "default"; select bloodsiren_in + waveform_out directly.
EOF

echo "Wrote $OUT"
echo "blood: $blood_link -> card $blood_card ($(card_id "$blood_card"))"
echo "siren: $siren_link -> card $siren_card ($(card_id "$siren_card"))"
echo
echo "Waveform ALSA:"
echo "  input : bloodsiren_in"
echo "  output: waveform_out"

